///////////////////////////////////////////////////////////
//  MessageWindow.as
//  Macromedia ActionScript Implementation of the Class MessageWindow
//  Generated by Enterprise Architect
//  Created on:      18-okt-2010 14:43:21
//  Original author: Wouter Tengeler
///////////////////////////////////////////////////////////

package nl.themotionstudio.utils
{
	import flash.display.DisplayObject;
	import flash.display.DisplayObjectContainer;
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	import flash.text.TextField;
	
	import nl.themotionstudio.events.CustomEvent;
	/**
	 * @author Wouter Tengeler
	 * @version 1.0
	 * @created 18-okt-2010 14:43:21
	 */
	public class DebugWindow extends Sprite
	{
	    private var m_oContainer: DisplayObjectContainer;
	    private var m_txtMessage: TextField;
		private var m_oBorder:Sprite;
		private var m_iWidth:int;
		private var m_iHeight:int;
		private var count : uint = 0;

		public function DebugWindow(p_iWidth:int, p_iHeight:int)
		{
			super();
			m_iWidth = p_iWidth;
			m_iHeight = p_iHeight;
			m_oContainer = null;
			drawBorder();
			m_txtMessage = new TextField();
			m_txtMessage.x = 3;
			m_txtMessage.y = 3;
			m_txtMessage.width = p_iWidth - 8;
			m_txtMessage.height = p_iHeight - 8;
			m_txtMessage.border = true;
			m_txtMessage.wordWrap = true;
			addChild(m_txtMessage);
		}

	    /**
	     * 
	     * @param p_sMessage
	     */
	    public function showMessage(p_sMessage:String): void
	    {
			if (count > 6) { clear(); count = 0; }
			m_txtMessage.appendText(p_sMessage + '\n');
			count ++;
	    }
		
		public function clear() : void
		{
			m_txtMessage.text = '';
		}

	    /**
	     * 
	     * @param p_oContainer
	     */
	    public function show(p_oContainer:DisplayObjectContainer): void
	    {
			hide();
			m_oContainer = p_oContainer;
			if (null != m_oContainer) { m_oContainer.addChild(this); }
	    }

	    public function hide(): void
	    {
			if ((null != m_oContainer) && (m_oContainer.contains(this))) { m_oContainer.removeChild(this); }
	    }

		private function drawBorder():void
		{
			m_oBorder = new Sprite();
			m_oBorder.graphics.beginFill(0xffffff);
			m_oBorder.graphics.lineStyle(2, 0x000000);
			m_oBorder.graphics.drawRect(0, 0, m_iWidth, m_iHeight);
			m_oBorder.addEventListener(MouseEvent.MOUSE_DOWN, handleMouseDown);
			m_oBorder.addEventListener(MouseEvent.MOUSE_UP, handleMouseUp);
			addChild(m_oBorder);
		}
		
		private function handleMouseDown(p_oEvent:MouseEvent):void {
			this.startDrag();
		}
		private function handleMouseUp(p_oEvent:MouseEvent):void {
			this.stopDrag();
		}

	}

}