///////////////////////////////////////////////////////////
//  OverlayEvent.as
//  Macromedia ActionScript Implementation of the Class OverlayEvent
//  Generated by Enterprise Architect
//  Created on:      16-jun-2011 12:30:25
//  Original author: Wouter Tengeler
///////////////////////////////////////////////////////////

package nl.funnymessages.overlay
{
	import nl.themotionstudio.events.CustomEvent;

	/**
	 * @author Wouter Tengeler
	 * @version 1.0
	 * @created 16-jun-2011 12:30:25
	 */
	public class OverlayEvent extends CustomEvent
	{
		public static const OVERLAY_EVENT_FILTER_START:String = 'OverlayEventFilterStart';
		public static const OVERLAY_EVENT_FILTER_END:String = 'OverlayEventFilterEnd';
		public static const OVERLAY_EVENT_SPEECH_START:String = 'OverlayEventSpeechStart';
		public static const OVERLAY_EVENT_SPEECH_END:String = 'OverlayEventSpeechEnd';
		
		public function OverlayEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false, eventObj:Object = null) {
			super(type, bubbles, cancelable, eventObj);

		}

	    public override function toString(): String
	    {
			return formatToString("OverlayEvent", "type", "bubbles", "cancelable", "eventPhase", "eventObj");
	    }

	}//end OverlayEvent

}