///////////////////////////////////////////////////////////
//  Overlay.as
//  Macromedia ActionScript Implementation of the Class Overlay
//  Generated by Enterprise Architect
//  Created on:      16-jun-2011 12:24:15
//  Original author: Wouter Tengeler
///////////////////////////////////////////////////////////

package nl.funnymessages.overlay
{
	import flash.display.Sprite;
	import nl.funnymessages.overlay.OverlayEvent;

	/**
	 * @author Wouter Tengeler
	 * @version 1.0
	 * @created 16-jun-2011 12:24:15
	 */
	public class Overlay extends Sprite
	{
		private var m_iId:uint;
		
		public function Overlay() {
			m_iId = parseId();
		}

	    /**
	     * 
	     * @param uint p_iType
	     * @param OverlayEventTrigger p_oTrigger
	     */
	    public function addEventType(p_iType:uint, p_oTrigger:OverlayEventTrigger): void
	    {
			throw new Error('method should be overridden by child class');
	    }
		
		/**
		 * the id of this overlay (readonly)
		 */
		public function get id():uint {
			return m_iId;
		}
		
		protected function parseId():uint {
			throw new Error('method should be overridden by child class');
		}

	}//end Overlay

}